<?php
/* Do Not Edit This File */
return [
    'key' => env('APP_MASTER', '34185625'),
    'file_size'=>2048,
    'printer'=>'network',
    'captcha' => env('CAPTCHA_SECURITY', null),
     'delay' =>1500,
];